### ISSUE TITLE
Unable to install helm chart

### ISSUE THREAD

**Issue by RC1140** [saferwall/saferwall#211]
Hi

When attempting to install the helm chart I get the following error

manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-instal"
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CouchbaseCluster" in version "couchbase.com/v1"

Reading up a bit on the error led me to the conclusion that the cluster is not being installed correctly. 

Is this a known issue with saferwall or do I just need a specific set of steps to get the chart installed.

Kind Regards

**Comment by LordNoteworthy** [comment]
Hello @RC1140 

That is a known issue on the couchbase helm chart. It happens because helm attempt to deploy the couchbase-cluster before deploying the operator.

Can you try something please:

1. Try disabling the couchbase-cluster by setting the `couchbase-cluster.enabled` to false in the `values.yaml`. Then run the install command.
2. After the installation succeeds, try to set the value back to true and run an upgrade command.

Apologies for the bug. I will put some more effort on easing the installation process.

**Comment by RC1140** [comment]
Hi @LordNoteworthy 

Yeah thanks , thats what I found as well but I couldnt work out how to get past the issue (tried commenting out sections as well). Will try the settings you mentioned and get back to you.

Appreciate the assitance

**Comment by LordNoteworthy** [comment]
Hi @RC1140 

That's coming for Prometheus-operator, apologies for that. I am currently fixing it.

I am also updating the doc: 
https://github.com/saferwall/saferwall/blob/master/docs/BUILDING.md

I will let you know when it is done.

You deploying locally in minikube or cloud ?

**Comment by RC1140** [comment]
Hi

Thanks for the updates , i was using minikube just to get the system tested and running easily but in the end I have a local on prem cluster that I will most likely deploy to. Trying to avoid the cloud for costing at the moment.

I think I got everything mostly worked out and deployed , I ran out of capacity while testing in minikube for elastic search so I was planning in testing without elastic this evening.

**Comment by RC1140** [comment]
Hi
Had a look at the build instructions for minikube and it looks like what I came up with (you can see the WIP commit i pushed) , the main thing its missing is that it doesnt build the containers in the minikube env i.e. eval (minikube docker-env), without that the helm will not run as it will never find the images. Also it seems your make commands command clear out the docker env variables that are set by that command so i tended to run the build commands manually.

**Comment by RC1140** [comment]
There is also an errant sudo command in the consumer docker build file that needs to be removed for it to compile

**Comment by LordNoteworthy** [comment]
Hey  @RC1140 

Well first, thanks for a lot for the catch 👍 regarding the:
- eval (minikube docker-env), and
- the sudo command in consumer

_Also it seems your make commands command clear out the docker env variables that are set by that command so i tended to run the build commands manually._
Oh, interesting! I am looking into this.

Cheers,

**Comment by RC1140** [comment]
Appreciate all the changes you made so far , I meant to submit pull requests but you tend to commit the fixes faster than me :)

Not sure if you saw , but I left a note on your last commit as there is another issue in the helm chart regarding the selection of the aws-efs/nfs storage setup.

https://github.com/saferwall/saferwall/commit/dbe82214056717e66c5af1221691c4073bde1f33#comments

**Comment by LordNoteworthy** [comment]
Thanks again  :)

I saw it, doing some tests to fix it. Will get back to you soon.

**Comment by RC1140** [comment]
I ended up debugging and fixing it will try and push the commit a bit later, it does require renaming the section in  the values.yaml so that they dont use '-' which go templates dont like.

**Comment by LordNoteworthy** [comment]
True, that's what I figured out yesterday and changes it to use `index`, and I taught that fixed it. So I was wrong.

I did not yet commit the manifest below, but I guess it might be good to add a check to just don't deploy the pvc if the user did not yet explicitly set the values.

```yaml
{{- if or (index .Values "efs-provisioner" "enabled") (index .Values "nfs-server-provisioner" "enabled") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "saferwall.fullname" . }}-samples
  {{- if index .Values "efs-provisioner" "enabled" }}
  annotations:
    volume.beta.kubernetes.io/storage-class: aws-efs
  {{- end }}
spec:
  {{- if index .Values "efs-provisioner" "enabled" }}
  storageClassName: aws-efs
  {{- else if index .Values "nfs-server-provisioner" "enabled" }}
  storageClassName: nfs
  {{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{- end }}
```

 I will wait for your PR. 

Cheers.
